// Generated by sqltyper from editions.sql.
// Do not edit directly. Instead, edit editions.sql and re-run sqltyper.


import { ClientBase, Pool } from 'pg'

export async function editions(
  client: ClientBase | Pool
): Promise<Array<{ 'id': number; 'locale': string | null; 'pg_language': string | null; 'name': string | null; 'abbrev': string | null }>> {
    const result = await client.query(`\
SELECT * FROM editions;
`)
    return result.rows
}
